### ISSUE TITLE
Unable to run Cucumber with Serenity feature files directly from IntelliJ - NullPointerException

### ISSUE THREAD

**Issue by havuong** [havuong/serenity-cucumber-parallel-screenplay#1]
`java.lang.NullPointerException
	at net.thucydides.core.steps.StepEventBus.updateOverallResults(StepEventBus.java:725)
	at net.serenitybdd.screenplay.EventBusInterface.updateOverallResult(EventBusInterface.java:34)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:217)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:161)
	at com.liquid.cucumber.steps.SignInSteps.userIsARegisteredMember(SignInSteps.java:30)
	at ✽.that Mary is a registered PTE(D:/IdeaProjects/serenity-cucumber-parallel-screenplay/src/test/resources/features/signin/sign_in_with_existing_account.feature:8)
`

**Comment by havuong** [comment]
**[Solution]**
IntelliJ provides excellent integrated support for Cucumber feature files. You can even run features simply by right-clicking on the feature file. But this won’t work when you are using Cucumber with Serenity, as Serenity needs to instrument the feature file before execution. Fortunately, this is easy to fix. Here’s how:

- Click on the feature file you want to run
- In the Run menu Select Run…
- In the contextual menu, select the feature, then “Edit…”
- You should now see the ‘Edit Configuration Settings’ window. Set the main class to ‘net.serenitybdd.cucumber.cli.Main’
- Change the Glue field to the root package of your project (or of your step definitions)
- Click Apply

Now you can run your feature directly by right-clicking on the feature file.

From https://johnfergusonsmart.com/running-cucumber-serenity-feature-files-directly-intellij/
